var fs=require("graceful-fs"),request=require("request"),path=require("path"),log=require("npmlog"),async=require("async"),mkdirp=require("mkdirp"),shelljs=require("shelljs"),extract=require("extract-zip"),appdata=require("./cli-appdata");
(function(){function p(){this.templates=[];this.libraries=[]}var u=path.join(__dirname,"json/templates_all.json"),g=new appdata,v=g.getConfig(!0).templatesServer||"";p.prototype={setTemplatesList:function(a){function q(a,m){var k=g.getConfig(!0);for(index in a){var e=a[index];if(e.hasOwnProperty("profile")&&-1!==e.profile.indexOf(k.profile)&&e.openLevel<=k.openLevel){var l=b.templates.filter(function(a){return a.id===e.id});if(0==l.length)b.templates.push(e);else for(prop in e)l[0][prop]=e[prop]}}setImmediate(m)}
var b=this;async.waterfall([function(a){log.verbose("generate#setTemplatesFromLocal()");var b=fs.readFileSync(u,"utf8");try{var k=JSON.parse(b).templates;setImmediate(a,null,k)}catch(e){return a(Error("JSON Parse Error:",e))}}.bind(b),q.bind(b),function(a){log.verbose("generate#setTemplatesFromServer()");request(v,function(m,k,e){if(m||200!=k.statusCode)setImmediate(a,null,{});else{try{var l=JSON.parse(e).templates;b.templates=b.templates.concat(l)}catch(g){setImmediate(a,null,{})}setImmediate(a,
null,l)}})}.bind(b),q.bind(b)],a)},getTemplatesList:function(a){return a&&"function"===typeof a?a(null,this.templates):this.templates},getTemplatesBy:function(a,g,b){var r=this.templates.filter(function(b){return b[a].toLowerCase()===g.toLowerCase()});return b&&"function"===typeof b?b(null,r):r},generate:function(a,q,b){function r(c){return n.templates.filter(function(a){return a.id===c})}function m(c,f){log.verbose("generate#_processTemplate()","processing Template:",c);a.version=a.version||"0.0.0";
var d=r(c)[0];if(!d)return f();if(d.files)try{var h=JSON.stringify(d.files),h=h.replace(/@PLUGINDIR@/g,g.getAppDir()).replace(/\\/g,"/"),h=h.replace(/@VERSION@/g,a.version);d.files=JSON.parse(h)}catch(b){return f(b,Error("JSON Parse Error : template data is invalid!!"))}d.files=d.files||[];d.deps=d.deps||[];async.series([async.forEachSeries.bind(this,d.deps,m),async.forEachSeries.bind(this,d.files,k)],f)}function k(c,a){log.verbose("generate#_processSourceItem()","processing Source Item:",c);c.url?
(c.at=c.at||c.prefixToAdd?s.destination+"/"+(c.at||c.prefixToAdd):s.destination,".zip"===path.extname(c.url)?e(c,a):fs.stat(c.url,function(d,h){d?a(d):h.isDirectory()?l(c,a):h.isFile()?p(c,a):a(Error("Don't know how to handle '"+c.url+"'"))})):setImmediate(a)}function e(c,a){log.verbose("generate#_porcessZipFile()","processing:",c.url);async.series([function(d){if("http"===c.url.substr(0,4)){var a=path.join(g.getAppDir(),"templates/built-in",path.basename(c.url)),b=path.join(g.getPath(),"download",
path.basename(c.url));if(fs.existsSync(a))c.url=a,setImmediate(d);else if(fs.existsSync(b)){var f=fs.statSync(b);request.head(c.url,function(a,h){a||200!=h.statusCode||f.size!=h.headers["content-length"]||(c.url=b);setImmediate(d)})}else setImmediate(d)}else setImmediate(d)}.bind(n),function(a){try{log.verbose("generate#_fetchFile()","download path :",c.url);var b=c.url,f=path.join(g.getPath(),"download");fs.existsSync(b)?setImmediate(a):"http"!==b.substr(0,4)?setImmediate(a,Error("Source '"+b+"' does not exists")):
(fs.existsSync(f)||mkdirp(f),c.url=path.join(f,path.basename(c.url)),request(b).pipe(fs.createWriteStream(c.url).on("close",a)))}catch(e){log.error("Generate#_fetchFile()",e),setImmediate(a,e)}}.bind(n),function(a){log.verbose("generate#_extractZip()","destination:",c.at);c.at?fs.existsSync(c.url)?extract(c.url,{dir:c.at},a):setImmediate(a,Error("Cannot find the archive file : "+c.url)):setImmediate(a)}.bind(n)],a)}function l(c,a){log.verbose("generate#_processFolder()","Processing:",c.url);async.series([mkdirp.bind(null,
c.at),async.forEachSeries.bind(n,shelljs.ls("-R",c.url),function(a,b){fs.lstatSync(c.url+"/"+a).isFile()?(mkdirp.sync(path.dirname(c.at+"/"+a)),shelljs.cp("-f",c.url+"/"+a,c.at+"/"+a),async.forEachSeries(s.substitutions||[],function(b,f){if((new RegExp(b.fileRegexp)).test(a))t(c.at+"/"+a,b,f);else return setImmediate(f)},b)):setImmediate(b)})],function(c){setImmediate(a,c)})}function p(a,b){log.verbose("generate#_processFile()","Processing:",a.url);mkdirp.sync(a.at);shelljs.cp("-f",a.url,a.at);async.forEachSeries(s.substitutions||
[],function(b,f){if((new RegExp(b.fileRegexp)).test(file))t(a.at+"/"+file,b,f);else return setImmediate(f)},b)}function t(a,b,d){function e(a,b,c,d){log.verbose("_applyJsonSubstitutions()","json:",b,"in",a);async.waterfall([fs.readFile.bind(null,a,{encoding:"utf8"}),function(d,e){d=JSON.parse(d);var f;Object.keys(b).forEach(function(a){if(d.hasOwnProperty(a)||c&&c[a])d[a]=b[a],f=!0});f?fs.writeFile(a,JSON.stringify(d,null,2),{encoding:"utf8"},e):setImmediate(e)}],d)}function g(a,b,c){log.verbose("_applyVarsSubstitutions()",
"variables in",a);async.waterfall([fs.readFile.bind(null,a,{encoding:"utf8"}),function(c,d){Object.keys(b).forEach(function(a){c=c.replace("${"+a+"}",b[a])});fs.writeFile(a,c,{encoding:"uft8"},d)}],c)}function k(a,c,b){log.verbose("_applyRegexpSubstitutions()","word in",a);async.waterfall([fs.readFile.bind(null,a,{encoding:"utf8"}),function(b,d){Object.keys(c).forEach(function(a){b=b.replace(new RegExp(a,"g"),c[a])});fs.writeFile(a,b,{encoding:"utf8"},d)}],b)}log.verbose("_substitue()","file:",a);
async.series([function(d){b.json?e(a,b.json,b.add,d):setImmediate(d)},function(d){b.vars?g(a,b.vars,d):setImmediate(d)},function(d){b.regexp?k(a,b.regexp,d):setImmediate(d)}],d)}log.verbose("generate()","options:",a);var n=this,s={substitutions:q,destination:a.dstPath};async.series([async.forEachSeries.bind(n,a.tmplNames,m)],b)}};"undefined"!==typeof module&&module.exports&&(module.exports=new p)})();
