var async=require("async"),child_process=require("child_process"),fs=require("fs"),log=require("npmlog"),net=require("net"),path=require("path"),shelljs=require("shelljs"),stream=require("stream"),Validator=require("jsonschema").Validator;
(function(){function l(b){log.silly("NovacomDB#_getNovacomPath()");var a="novacom";"undefined"!==typeof b&&!0===b&&(a="novacomd");if("undefined"===typeof l[a]){var k="win32"===process.platform?a+".exe":a;b=path.resolve(__dirname,"..","bin",k);k=path.resolve(__dirname,"..",a,process.platform,k);fs.existsSync(b)?l[a]=b:fs.existsSync(k)?l[a]=k:log.verbose("No "+a+" in path ("+b+", "+k+")")}log.verbose("NovacomDB#_getNovacomPath()#",a,l[a]);return l[a]}function t(b){log.verbose("NovacomUSB#_getFreePort()");
var a=net.createServer();a.on("error",function(a){log.info("NovacomUSB#_getFreePort()","error!");return setImmediate(b,a)});a.listen(0,function(){port=a.address().port;a.close(function(){log.info("NovacomUSB#_getFreePort()","port",port);return setImmediate(b,null,port)})})}function q(b,a,k){log.verbose("NovacomUSB#_checkSchema()","data:",b,"schemaFile",a);var g="/"+path.basename(a).split(".")[0],c={id:"test",type:"array",items:{$ref:g+"Schema"}};if(fs.statSync(a).isFile()){var h=fs.readFileSync(a,
"utf8"),f,d,e,r=new Validator;try{d=JSON.parse(h);r.addSchema(d,g);if((f=r.validate(b,c))&&0<f.errors.length){e="";e=e.concat("Invalid data! schema:",a);for(idx in f.errors){e=e.concat("\n");var m=f.errors[idx].property+" "+f.errors[idx].message;null!==(f=/instance\[*.*\]*\./g.exec(m))&&(m=m.substring(f[0].length));e=e.concat(m)}log.info("NovacomUSB#_checkSchema()","error!");return setImmediate(k,Error(e))}return setImmediate(k,null,b)}catch(p){return log.info("NovacomUSB#_checkSchema()","error!"),
setImmediate(k,Error("Invalid JSON Schema"))}}else return log.verbose("Resolver#save()#_checkSchema()",a,"is not exist!"),setImmediate(k,null,b)}var n={};"undefined"!==typeof module&&module.exports&&(module.exports=n);log.heading="novacom-usb";log.level="verbose";n.log=log;var s=function(b,a){log.verbose("NovacomUSB#_getNovacomDeviceList()","options",b);async.parallel({keys:function(a){var b=path.resolve(process.env.HOME||process.env.USERPROFILE,".ssh"),c=path.resolve(__dirname,"setting-files","keys");
if(!fs.existsSync(c))return a();fs.readdir(c,function(h,f){if(h)return a(h);f.forEach(function(d){fs.existsSync(path.join(b,d))||shelljs.cp("-rf",path.join(c,d),b)});a()})},auths:function(a){var g=path.join(b.appdir,"novacom-usb-auth.json"),c=path.resolve(__dirname,"setting-files","novacom-usb-auth.json");if(!fs.existsSync(c))return a();fs.existsSync(g)||shelljs.cp("-rf",c,b.appdir);log.verbose("Resolver#load#_readFile()","<<< "+g);fs.readFile(g,"utf8",function(c,f){if(c&&"ENOENT"===c.code)return setImmediate(a,
null,[]);var d=JSON.parse(f);return Array.isArray(d)?setImmediate(q,d,path.join(__dirname,"schema/NovacomUSBAuth.schema"),a):(log.info("NovacomUSB#_getNovacomDeviceList()","error"),setImmediate(a,Error("Incorrect file format.")))})},devices:function(a){var b=new net.Socket,c,h="";b.on("error",function(a){c=a});b.on("close",function(){if("undefined"!==typeof c)return log.info("Novacomd daemon is not running ...!",c),setImmediate(a,null,[]);var b=[],d,e,g,m,p;p=h.split("\n");for(e in p)if(0!==p[e].trim().length){d=
p[e].split(" ");if(5===d.length||6===d.length)m=d[4].split(":"),2===m.length&&m[1]&&(g=parseInt(m[0]));d="undefined"!==typeof g&&d[5]?{order:-1,profile:"watch",index:e,id:d[1],name:d[2],type:d[3],transport:d[2],device_mode:d[5],description:"",host:"127.0.0.1",port:g,files:"stream",noPortForwarding:!1,indelible:!0,conn:["novacom","ssh"]}:{order:-1,profile:"watch",index:e,id:d[1],name:d[2],type:d[3],transport:d[2],description:"",host:"127.0.0.1",port:void 0,files:"stream",noPortForwarding:!1,indelible:!0,
conn:["novacom"]};"usb"===d.transport.slice(0,3)&&(d.type="w2-linux");b.push(d)}return setImmediate(q,b,path.join(__dirname,"schema/NovacomUSBDevice.schema"),a)});b.on("data",function(a){h+=a.toString();b.end()});return b.connect({port:6968})}},function(b,g){var c,h,f,d={},e=g.devices;if(b)return log.info("NovacomUSB#_getNovacomDeviceList()","err",b),setImmediate(a,b);for(c in g.auths)d[g.auths[c].id]=g.auths[c];for(c in e)h=e[c].id,f="root"===e[c].device_mode?"*"+e[c].type+"-root*":"developer"===
e[c].device_mode?"*"+e[c].type+"-developer*":"*"+e[c].type+"*",d.hasOwnProperty(h)?(d[h].hasOwnProperty("username")&&(e[c].username=d[h].username),d[h].hasOwnProperty("password")&&(e[c].password=d[h].password),d[h].hasOwnProperty("privateKey")&&(e[c].privateKey=d[h].privateKey)):d.hasOwnProperty(f)&&(d[f].hasOwnProperty("username")&&(e[c].username=d[f].username),d[f].hasOwnProperty("password")&&(e[c].password=d[f].password),d[f].hasOwnProperty("privateKey")&&(e[c].privateKey=d[f].privateKey));return setImmediate(a,
null,e)})},u=function(b,a,k){b=l()+" run file:///usr/bin/which "+a+" -d "+b;child_process.exec(b,{encoding:"utf8",timeout:1E3,maxBuffer:204800,killSignal:"SIGTERM",cwd:null,env:null},function(a,b,h){var f;b&&(f=b.toString());setImmediate(k,a,f)}).stdin.end()};n.getDeviceList=s;n.connectTunnel=function(b,a){if("undefined"!==typeof b.port||"usb"!==b.transport)return setImmediate(a,null,b);t(function(k,g){var c=l()+" -P -f "+g+":10022 -d "+b.id;child_process.exec(c,{encoding:"utf8",timeout:1E3,maxBuffer:204800,
killSignal:"SIGTERM",cwd:null,env:null},function(a,b,d){});b.port=g;return setImmediate(a,null,b)})};n.waitDeviceConnect=function(b,a){log.verbose("NovacomUSB#_waitDeviceConnect()","options",b);if(!1===("object"===typeof b&&"boolean"===typeof b.waitForDevice?b.waitForDevice:!1))return setImmediate(a);var k=!0,g=0,c,h=setInterval(function(){s(b,function(b,e){if(b)return setImmediate(a,b);Array.isArray(e)&&e.forEach(function(b){c=b.transport;if("usb"===c.slice(0,3)||"tcp"===c.slice(0,3))process.stdout.write("\b \n\r"),
clearInterval(h),setImmediate(a)});0==e.length&&!0==k&&(process.stdout.write("\nwaiting for device...."),k=!1)});if(!1==k){var f=g++%3;0===f?process.stdout.write("\b/"):1===f?process.stdout.write("\b-"):process.stdout.write("\b\\")}},200)};n.getNovacomPath=l;n.getNovacomDaemonPath=function(){return l(!0)};n.getNovacomUser=function(b,a){var k=l()+' run "file:///usr/bin/id -un" -d '+b;child_process.exec(k,{encoding:"utf8",timeout:1E3,maxBuffer:204800,killSignal:"SIGTERM",cwd:null,env:null},function(b,
c,h){var f;c&&(f=c.toString());setImmediate(a,b,f)}).stdin.end()};n.runDeviceCommand=function(b,a,k,g,c,h){var f={},d={};g?g instanceof stream.Stream?(log.silly("Session#run()","stdout: stream"),f.stdout=g.write,d.stdout=g):g instanceof Function?(log.silly("Session#run()","stdout: function"),f.stdout=g):setImmediate(h,Error("Invalid novacom stdout: "+util.inspect(g))):(log.silly("Session#run()","stdout: none"),f.stdout=function(){});c?c instanceof stream.Stream?(log.silly("Session#run()","stderr: stream"),
f.stderr=c.write,d.stderr=c):c instanceof Function?(log.silly("Session#run()","stderr: function"),f.stderr=c):setImmediate(h,Error("Invalid novacom stderr: "+util.inspect(c))):(log.silly("Session#run()","stderr: none"),f.stderr=function(){});a=a.replace(/\"/g,'\\"');var e;async.series([function(c){e=" run file://";"/"!==a[0]?(cmdTokens=a.split(" "),u(b,cmdTokens[0],function(b,d){if(!d)return setImmediate(c,Error("Unable to run "+cmdTokens[0]));cmdTokens[0]=d;a=cmdTokens.join(" ");e+=a;c()})):(e+=
a,c())},function(b){var a=child_process.spawn(l(),[e],{stdio:["ignore","pipe","pipe"]});a.stderr.on("data",function(a){f.stderr.bind(d.stderr)(a)});a.stdout.on("data",function(a){f.stdout.bind(d.stdout)(a)});a.on("exit",function(a){setImmediate(b)})}],function(a){setImmediate(h,a)})}})();
